import dynamic from "next/dynamic";

// Registry mapping
// We use dynamic imports to keep the initial bundle size small as the library grows
export const registry = {
  header1: dynamic(() => import("./headers/Header1")),
  header2: dynamic(() => import("./headers/Header2")),
  header3: dynamic(() => import("./headers/Header3")), // Glassmorphism
  header4: dynamic(() => import("./headers/Header4")), // Corporate
  header5: dynamic(() => import("./headers/Header5")), // Modern SaaS (Shadcn Style)
  header6: dynamic(() => import("./headers/Header6")),
  header7: dynamic(() => import("./headers/Header7")),
  header8: dynamic(() => import("./headers/Header8")),
  header9: dynamic(() => import("./headers/Header9")),
  header10: dynamic(() => import("./headers/Header10")),

  // Hero Section
  hero1: dynamic(() => import("./heroes/Hero1")),
  hero2: dynamic(() => import("./heroes/Hero2")),
  hero3: dynamic(() => import("./heroes/Hero3")), // Abstract Shapes
  hero4: dynamic(() => import("./heroes/Hero4")), // Grid Layout
  hero5: dynamic(() => import("./heroes/Hero5")),
  hero6: dynamic(() => import("./heroes/Hero6")),
  hero7: dynamic(() => import("./heroes/Hero7")),
  hero8: dynamic(() => import("./heroes/Hero8")),
  hero9: dynamic(() => import("./heroes/Hero9")),
  hero10: dynamic(() => import("./heroes/Hero10")),
  about1: dynamic(() => import("./abouts/About1")),
  about2: dynamic(() => import("./abouts/About2")),
  about3: dynamic(() => import("./abouts/About3")),
  about4: dynamic(() => import("./abouts/About4")),
  about5: dynamic(() => import("./abouts/About5")),
  about6: dynamic(() => import("./abouts/About6")),
  about7: dynamic(() => import("./abouts/About7")),
  about8: dynamic(() => import("./abouts/About8")),
  about9: dynamic(() => import("./abouts/About9")),
  about10: dynamic(() => import("./abouts/About10")),
  contact1: dynamic(() => import("./contact/Contact1")),
  contact2: dynamic(() => import("./contact/Contact2")),
  contact3: dynamic(() => import("./contact/Contact3")),
  contact4: dynamic(() => import("./contact/Contact4")),
  contact5: dynamic(() => import("./contact/Contact5")),
  contact6: dynamic(() => import("./contact/Contact6")),
  contact7: dynamic(() => import("./contact/Contact7")),
  contact8: dynamic(() => import("./contact/Contact8")),
  contact9: dynamic(() => import("./contact/Contact9")),
  contact10: dynamic(() => import("./contact/Contact10")),
  faq1: dynamic(() => import("./faq/FAQ1")),
  faq2: dynamic(() => import("./faq/FAQ2")),
  faq3: dynamic(() => import("./faq/FAQ3")),
  faq4: dynamic(() => import("./faq/FAQ4")),
  faq5: dynamic(() => import("./faq/FAQ5")),
  faq6: dynamic(() => import("./faq/FAQ6")),
  faq7: dynamic(() => import("./faq/FAQ7")),
  faq8: dynamic(() => import("./faq/FAQ8")),
  faq9: dynamic(() => import("./faq/FAQ9")),
  faq10: dynamic(() => import("./faq/FAQ10")),
  team1: dynamic(() => import("./team/Team1")),
  team2: dynamic(() => import("./team/Team2")),
  team3: dynamic(() => import("./team/Team3")),
  team4: dynamic(() => import("./team/Team4")),
  team5: dynamic(() => import("./team/Team5")),
  team6: dynamic(() => import("./team/Team6")),
  team7: dynamic(() => import("./team/Team7")),
  team8: dynamic(() => import("./team/Team8")),
  team9: dynamic(() => import("./team/Team9")),
  team10: dynamic(() => import("./team/Team10")),
  services1: dynamic(() => import("./services/Services1")),
  services2: dynamic(() => import("./services/Services2")),
  services3: dynamic(() => import("./services/Services3")),
  services4: dynamic(() => import("./services/Services4")),
  services5: dynamic(() => import("./services/Services5")),
  services6: dynamic(() => import("./services/Services6")),
  services7: dynamic(() => import("./services/Services7")),
  services8: dynamic(() => import("./services/Services8")),
  services9: dynamic(() => import("./services/Services9")),
  services10: dynamic(() => import("./services/Services10")),
  projects1: dynamic(() => import("./projects/Projects1")),
  projects2: dynamic(() => import("./projects/Projects2")),
  projects3: dynamic(() => import("./projects/Projects3")),
  projects4: dynamic(() => import("./projects/Projects4")),
  projects5: dynamic(() => import("./projects/Projects5")),
  projects6: dynamic(() => import("./projects/Projects6")),
  projects7: dynamic(() => import("./projects/Projects7")),
  projects8: dynamic(() => import("./projects/Projects8")),
  projects9: dynamic(() => import("./projects/Projects9")),
  projects10: dynamic(() => import("./projects/Projects10")),
  pricing1: dynamic(() => import("./pricing/Pricing1")),
  pricing2: dynamic(() => import("./pricing/Pricing2")),
  pricing3: dynamic(() => import("./pricing/Pricing3")),
  pricing4: dynamic(() => import("./pricing/Pricing4")),
  pricing5: dynamic(() => import("./pricing/Pricing5")),
  pricing6: dynamic(() => import("./pricing/Pricing6")),
  pricing7: dynamic(() => import("./pricing/Pricing7")),
  pricing8: dynamic(() => import("./pricing/Pricing8")),
  pricing9: dynamic(() => import("./pricing/Pricing9")),
  pricing10: dynamic(() => import("./pricing/Pricing10")),
  testimonials1: dynamic(() => import("./testimonials/Testimonials1")),
  testimonials2: dynamic(() => import("./testimonials/Testimonials2")),
  testimonials3: dynamic(() => import("./testimonials/Testimonials3")),
  testimonials4: dynamic(() => import("./testimonials/Testimonials4")),
  testimonials5: dynamic(() => import("./testimonials/Testimonials5")),
  testimonials6: dynamic(() => import("./testimonials/Testimonials6")),
  testimonials7: dynamic(() => import("./testimonials/Testimonials7")),
  testimonials8: dynamic(() => import("./testimonials/Testimonials8")),
  testimonials9: dynamic(() => import("./testimonials/Testimonials9")),
  testimonials10: dynamic(() => import("./testimonials/Testimonials10")),
  stats1: dynamic(() => import("./stats/Stats1")),
  stats2: dynamic(() => import("./stats/Stats2")),
  stats3: dynamic(() => import("./stats/Stats3")),
  stats4: dynamic(() => import("./stats/Stats4")),
  stats5: dynamic(() => import("./stats/Stats5")),
  stats6: dynamic(() => import("./stats/Stats6")),
  stats7: dynamic(() => import("./stats/Stats7")),
  stats8: dynamic(() => import("./stats/Stats8")),
  stats9: dynamic(() => import("./stats/Stats9")),
  stats10: dynamic(() => import("./stats/Stats10")),
  cta1: dynamic(() => import("./cta/Cta1")),
  cta2: dynamic(() => import("./cta/Cta2")),
  cta3: dynamic(() => import("./cta/Cta3")),
  cta4: dynamic(() => import("./cta/Cta4")),
  cta5: dynamic(() => import("./cta/Cta5")),
  cta6: dynamic(() => import("./cta/Cta6")),
  cta7: dynamic(() => import("./cta/Cta7")),
  cta8: dynamic(() => import("./cta/Cta8")),
  cta9: dynamic(() => import("./cta/Cta9")),
  cta10: dynamic(() => import("./cta/Cta10")),
  blog1: dynamic(() => import("./blog/Blog1")),
  blog2: dynamic(() => import("./blog/Blog2")),
  blog3: dynamic(() => import("./blog/Blog3")),
  blog4: dynamic(() => import("./blog/Blog4")),
  blog5: dynamic(() => import("./blog/Blog5")),
  blog6: dynamic(() => import("./blog/Blog6")),
  blog7: dynamic(() => import("./blog/Blog7")),
  blog8: dynamic(() => import("./blog/Blog8")),
  blog9: dynamic(() => import("./blog/Blog9")),
  blog10: dynamic(() => import("./blog/Blog10")),
  footer1: dynamic(() => import("./footers/Footer1")),
  footer2: dynamic(() => import("./footers/Footer2")),
  footer3: dynamic(() => import("./footers/Footer3")),
  footer4: dynamic(() => import("./footers/Footer4")),
  footer5: dynamic(() => import("./footers/Footer5")),
  footer6: dynamic(() => import("./footers/Footer6")),
  footer7: dynamic(() => import("./footers/Footer7")),
  footer8: dynamic(() => import("./footers/Footer8")),
  footer9: dynamic(() => import("./footers/Footer9")),
  footer10: dynamic(() => import("./footers/Footer10")),

  // Features Section
  menu1: dynamic(() => import("./menu/Menu1")),
  menu2: dynamic(() => import("./menu/Menu2")),
  menu3: dynamic(() => import("./menu/Menu3")),
  menu4: dynamic(() => import("./menu/Menu4")),
  menu5: dynamic(() => import("./menu/Menu5")),
  menu6: dynamic(() => import("./menu/Menu6")),
  menu7: dynamic(() => import("./menu/Menu7")),
  menu8: dynamic(() => import("./menu/Menu8")),
  menu9: dynamic(() => import("./menu/Menu9")),
  menu10: dynamic(() => import("./menu/Menu10")),
  gallery1: dynamic(() => import("./gallery/Gallery1")),
  gallery2: dynamic(() => import("./gallery/Gallery2")),
  gallery3: dynamic(() => import("./gallery/Gallery3")),
  gallery4: dynamic(() => import("./gallery/Gallery4")),
  gallery5: dynamic(() => import("./gallery/Gallery5")),
  gallery6: dynamic(() => import("./gallery/Gallery6")),
  gallery7: dynamic(() => import("./gallery/Gallery7")),
  gallery8: dynamic(() => import("./gallery/Gallery8")),
  gallery9: dynamic(() => import("./gallery/Gallery9")),
  gallery10: dynamic(() => import("./gallery/Gallery10")),
  productgrid1: dynamic(() => import("./products/ProductGrid1")),
  productgrid2: dynamic(() => import("./products/ProductGrid2")),
  productgrid3: dynamic(() => import("./products/ProductGrid3")),
  productgrid4: dynamic(() => import("./products/ProductGrid4")),
  productgrid5: dynamic(() => import("./products/ProductGrid5")),
  productgrid6: dynamic(() => import("./products/ProductGrid6")),
  productgrid7: dynamic(() => import("./products/ProductGrid7")),
  productgrid8: dynamic(() => import("./products/ProductGrid8")),
  productgrid9: dynamic(() => import("./products/ProductGrid9")),
  productgrid10: dynamic(() => import("./products/ProductGrid10")),
  legal1: dynamic(() => import("./legal/Legal1")),
  legal2: dynamic(() => import("./legal/Legal2")),
  legal3: dynamic(() => import("./legal/Legal3")),
  legal4: dynamic(() => import("./legal/Legal4")),
  legal5: dynamic(() => import("./legal/Legal5")),
  legal6: dynamic(() => import("./legal/Legal6")),
  legal7: dynamic(() => import("./legal/Legal7")),
  legal8: dynamic(() => import("./legal/Legal8")),
  legal9: dynamic(() => import("./legal/Legal9")),
  legal10: dynamic(() => import("./legal/Legal10")),
  appointment1: dynamic(() => import("./appointment/Appointment1")),
  appointment2: dynamic(() => import("./appointment/Appointment2")),
  appointment3: dynamic(() => import("./appointment/Appointment3")),
  appointment4: dynamic(() => import("./appointment/Appointment4")),
  appointment5: dynamic(() => import("./appointment/Appointment5")),
  appointment6: dynamic(() => import("./appointment/Appointment6")),
  appointment7: dynamic(() => import("./appointment/Appointment7")),
  appointment8: dynamic(() => import("./appointment/Appointment8")),
  appointment9: dynamic(() => import("./appointment/Appointment9")),
  appointment10: dynamic(() => import("./appointment/Appointment10")),
  heroSlider: dynamic(() => import("./heroes/HeroSlider")),
  teamDetailed: dynamic(() => import("./team/TeamDetailed")),
  contactMap: dynamic(() => import("./contact/ContactMap")),
};

export const getComponent = (category, id) => {
  // If category is provided (legacy or specific access)
  if (registry[category] && registry[category][id]) {
    return registry[category][id];
  }

  // Direct access (flat structure for new components)
  if (registry[id]) {
    return registry[id];
  }

  // Fallback for flat structure passed as category/id mismatch
  if (registry[category]) {
    return registry[category];
  }

  console.warn(`Component not found: ${id} (Category: ${category})`);
  return null;
};

export const getAvailableComponents = (category) => {
  if (!category) return Object.keys(registry);
  return Object.keys(registry).filter(key => key.startsWith(category));
};
